In [1]:
import numpy as np
import scipy.linalg as li

# a)

\begin{cases}
7x_1 + x_2 + x_3 = 7 \\
x_1 + 5x_2 + 2x_3 + x_4 = 0 \\
2x_1 + 3x_2 − 3x_3 + 3x_4 = −1 \\
3x_1 + 4x_2 + 5x_3 + 5x_4 = −2 
\end{cases}

In [2]:
a_A = np.array([[7, 1, 1, 0], [1, 5, 2, 1], [2, 3, -3, 3], [3, 4, 5, 5]])
a_b = np.array([7, 0, -1, -2]) 
a_A, a_b

(array([[ 7,  1,  1,  0],
        [ 1,  5,  2,  1],
        [ 2,  3, -3,  3],
        [ 3,  4,  5,  5]]),
 array([ 7,  0, -1, -2]))

In [3]:
lu, piv = li.lu_factor(a_A)
q, r = li.qr(a_A)
print("1)", "lu:", lu, "piv:", piv, sep="\n")
print("q:", q, "r:", r, sep="\n")

1)
lu:
[[ 7.          1.          1.          0.        ]
 [ 0.14285714  4.85714286  1.85714286  1.        ]
 [ 0.28571429  0.55882353 -4.32352941  2.44117647]
 [ 0.42857143  0.73529412 -0.7414966   6.07482993]]
piv:
[0 1 2 3]
q:
[[-0.8819171   0.38508734 -0.02724165 -0.27053254]
 [-0.12598816 -0.74659791  0.01108952 -0.65314284]
 [-0.25197632 -0.33793379 -0.80302587  0.42125781]
 [-0.37796447 -0.42438197  0.59521791  0.56811833]]
r:
[[-7.93725393 -3.77964473 -2.26778684 -2.77173947]
 [ 0.         -6.05923145 -2.21621695 -3.88230912]
 [ 0.          0.          5.38010458  0.57810148]
 [ 0.          0.          0.          3.45122223]]


In [4]:
x_lu = li.lu_solve((lu, piv), a_b)
Qb = np.matmul(q.T, a_b)
x_qr = np.linalg.solve(r,Qb)
print("3)", "решение lu:", x_lu, "решение qr:", x_qr, sep="\n")

3)
решение lu:
[ 1.  0. -0. -1.]
решение qr:
[ 1.00000000e+00  1.97230949e-16  6.19071437e-17 -1.00000000e+00]


# b)

\begin{matrix}
\begin{pmatrix}
4 & −6 & 0 & 8 & 0 & 0 \\
−6 & 8 & −12 & 0 & 16 & 0 \\
0 & −12 & 16 & 0 & 0 & 10 \\
8 & 0 & 0 & 20 & −8 & 0 \\
0 & 16 & 0 & −8 & 24 & −8 \\
0 & 0 & 10 & 0 & −8 & 28
\end{pmatrix}

\begin{vmatrix}
24 \\
54 \\
84 \\
48 \\
72 \\
158 
\end{vmatrix}
\end{matrix}

In [5]:
def create_second_a():
    first = np.zeros((3, 3),dtype=int)
    np.fill_diagonal(first, [8, 16, 10])
    second = np.zeros((3, 3), dtype=int)
    second_diag = np.array([-6, -12])
    np.fill_diagonal(second, [4, 8, 16])
    np.fill_diagonal(second[1:], second_diag)
    np.fill_diagonal(second[:,1:], second_diag)
    third = np.zeros((3, 3), dtype=int)
    np.fill_diagonal(third, np.arange(20, 29, 4))
    np.fill_diagonal(third[1:], np.array([-8, -8]))
    np.fill_diagonal(third[:,1:], np.array([-8, -8]))
    first_second = np.concatenate((second, first), axis=0)
    first_third = np.concatenate((first, third), axis=0)
    return np.concatenate((first_second, first_third), axis=1)

b_A = create_second_a()
b_b = np.array([24, 54, 84, 48, 72, 158]) 
b_A, b_b

(array([[  4,  -6,   0,   8,   0,   0],
        [ -6,   8, -12,   0,  16,   0],
        [  0, -12,  16,   0,   0,  10],
        [  8,   0,   0,  20,  -8,   0],
        [  0,  16,   0,  -8,  24,  -8],
        [  0,   0,  10,   0,  -8,  28]]),
 array([ 24,  54,  84,  48,  72, 158]))

In [6]:
lu, piv = li.lu_factor(b_A)
q, r = li.qr(b_A)
print("1)", "lu:", lu, "piv:", piv, sep="\n")
print("q:", q, "r:", r, sep="\n")

1)
lu:
[[  8.           0.           0.          20.          -8.
    0.        ]
 [  0.          16.           0.          -8.          24.
   -8.        ]
 [  0.          -0.75        16.          -6.          18.
    4.        ]
 [ -0.75         0.5         -0.75        14.5         11.5
    7.        ]
 [  0.           0.           0.625        0.25862069 -22.22413793
   23.68965517]
 [  0.5         -0.375        0.          -0.34482759  -0.76338247
   17.49806051]]
piv:
[3 4 2 4 5 5]
q:
[[-0.37139068  0.16483461  0.24187004  0.09188413  0.4890747   0.7271593 ]
 [ 0.55708601 -0.20038718  0.33216819 -0.66518046  0.29190919  0.10718407]
 [-0.          0.56237692 -0.5315766  -0.25101799  0.51681686 -0.26654986]
 [-0.74278135 -0.23270769  0.12819112 -0.54482741 -0.02560546 -0.2831916 ]
 [-0.         -0.74983589 -0.47406528  0.17878328  0.42506106  0.01918031]
 [-0.         -0.         -0.55445347 -0.39658776 -0.47661594  0.55510066]]
r:
[[-10.77032961   6.68503217  -6.68503217 -17.8267

In [7]:
x_lu = li.lu_solve((lu, piv), b_b)
Qb = np.matmul(q.T, b_b)
x_qr = np.linalg.solve(r,Qb)
print("3)", "решение lu:", x_lu, "решение qr:", x_qr, sep="\n")

3)
решение lu:
[1. 2. 3. 4. 5. 6.]
решение qr:
[1. 2. 3. 4. 5. 6.]


# c)

In [8]:
n = 5
c_A = np.zeros((n,n))
np.fill_diagonal(c_A, 2)    
np.fill_diagonal(c_A[1:], -1)
np.fill_diagonal(c_A[:,1:], -1)
c_b = np.zeros((n))
c_b[0] = 1
c_b[n-1] = -1
c_A, c_b

(array([[ 2., -1.,  0.,  0.,  0.],
        [-1.,  2., -1.,  0.,  0.],
        [ 0., -1.,  2., -1.,  0.],
        [ 0.,  0., -1.,  2., -1.],
        [ 0.,  0.,  0., -1.,  2.]]),
 array([ 1.,  0.,  0.,  0., -1.]))

In [9]:
lu, piv = li.lu_factor(c_A)
q, r = li.qr(c_A)
print("1)", "lu:", lu, "piv:", piv, sep="\n")
print("q:", q, "r:", r, sep="\n")

1)
lu:
[[ 2.         -1.          0.          0.          0.        ]
 [-0.5         1.5        -1.          0.          0.        ]
 [ 0.         -0.66666667  1.33333333 -1.          0.        ]
 [ 0.          0.         -0.75        1.25       -1.        ]
 [ 0.          0.          0.         -0.8         1.2       ]]
piv:
[0 1 2 3 4]
q:
[[-0.89442719 -0.35856858 -0.19518001 -0.12309149  0.13483997]
 [ 0.4472136  -0.71713717 -0.39036003 -0.24618298  0.26967994]
 [-0.          0.5976143  -0.58554004 -0.36927447  0.40451992]
 [-0.         -0.          0.68313005 -0.49236596  0.53935989]
 [-0.         -0.         -0.          0.73854895  0.67419986]]
r:
[[-2.23606798  1.78885438 -0.4472136   0.          0.        ]
 [ 0.         -1.67332005  1.91236577 -0.5976143   0.        ]
 [ 0.          0.         -1.46385011  1.95180015 -0.68313005]
 [ 0.          0.          0.         -1.3540064   1.96946386]
 [ 0.          0.          0.          0.          0.80903983]]


In [10]:
c, low = li.cho_factor(c_A)
print("2) c:", c, sep="\n")

2) c:
[[ 1.41421356 -0.70710678  0.          0.          0.        ]
 [-1.          1.22474487 -0.81649658  0.          0.        ]
 [ 0.         -1.          1.15470054 -0.8660254   0.        ]
 [ 0.          0.         -1.          1.11803399 -0.89442719]
 [ 0.          0.          0.         -1.          1.09544512]]


In [11]:
x_lu = li.lu_solve((lu, piv),c_b)
Qb = np.matmul(q.T,c_b)
x_qr = np.linalg.solve(r,Qb)
x_ch = li.cho_solve((c, low), c_b)
print("3)", "решение lu:", x_lu, "решение qr:", x_qr, "решение cholesky:", x_ch, sep="\n")

3)
решение lu:
[ 6.66666667e-01  3.33333333e-01 -8.32667268e-17 -3.33333333e-01
 -6.66666667e-01]
решение qr:
[ 0.66666667  0.33333333 -0.         -0.33333333 -0.66666667]
решение cholesky:
[ 6.66666667e-01  3.33333333e-01  9.61481343e-17 -3.33333333e-01
 -6.66666667e-01]
